### ISSUE TITLE
add banner to training page

### ISSUE THREAD

**Issue by samanthasunne** [ludstuen90/samanthasunne#62]
The Training page should have a banner of images, like the home page. I will send you the images - I'm not sure how you constructed the banner on the home page

**Comment by samanthasunne** [comment]
IMAGES:

IRE - square - 225x225

IRE - rectangle - 350x116

SPJ - square - 200x200

SPJ - rectangle - 412x122

Google - square - 225x225

Google - rectangle - 384x131

AU - square - 222x227

AU - rectangle - 587x86

AU - rectangle 2 - 1280x396

Data Narrative - rectangle -  306x165

BU - square - 225x225

BU - rectangle - 335x150

BU - rectangle 2 - 389x129

**Comment by ludstuen90** [comment]
Adding comment from email: The Tutorial banner should mirror the About banner -- it would be below the Tutorials/Upcoming Appearances section and above the Online Tutorials section.

**Comment by ludstuen90** [comment]
@samanthasunne  Here's a first iteration of the banner, I think it looks sharp! (The code on this branch will still have the current site layout, that will change a little bit when we complete #63 )

![image](https://user-images.githubusercontent.com/6817579/82131774-37d50600-97af-11ea-869d-880ebc37900a.png)

With respect to the ordering: I put the logos so that the visually strongest logos (more color, less whitespace) would be on the edges, and the the logos that have more whitespace in the middle, to try and create some balance.

Also, I know the "Online Tutorials" section is dynamic, but I put Boston University on the left, and i think the red there provides a nice contrast to the "Backgrounding: Why? How?" section.

![image](https://user-images.githubusercontent.com/6817579/82131777-3d325080-97af-11ea-8bec-b2609e3d1e28.png)

Also, just like the homepage banner, this banner scales nicely on mobile phones. 
![image](https://user-images.githubusercontent.com/6817579/82131778-3f94aa80-97af-11ea-9cd2-a15a732a3022.png)

**Comment by samanthasunne** [comment]
Great, let's go with that. Ideally I'd like there to be a bit less white space between the banner and the Upcoming Workshops section. But it's not a big deal

**Comment by ludstuen90** [comment]
How does this look?
