### ISSUE TITLE
change Upcoming Appearances alignment

### ISSUE THREAD

**Issue by samanthasunne** [ludstuen90/samanthasunne#63]
The Upcoming Appearances table on the training page looks weird.

Should the header "Upcoming Appearances" match "Tutorials" in size and style? Would that give "upcoming appearances" too much weight?

Should "U A" be in line with "Tutorials"?

Should table be in line with image?

**Comment by ludstuen90** [comment]
@samanthasunne  Here are a few initial options. I hear what you mean about making the table line up with the image, I think there are a few ways we can go. 

I think the options 1.d are the strongest, with the strongest being 1.d.1, then 1.d.2.

**Option 1.a: - two separate headlines above** 
Upcoming appearances given the same emphasis as Tutorials. 
![image](https://user-images.githubusercontent.com/6817579/82130948-64385480-97a6-11ea-83c9-87cc4aa9530f.png)

Visually I think this looks good, since if you scroll down, all the fonts have a similar emphasis: 
![image](https://user-images.githubusercontent.com/6817579/82130975-a9f51d00-97a6-11ea-8225-665c49e672a4.png)

If we want the top of the picture to line up with the top of the table, this is our easiest option, since the text elements are the same size. 

**Option 1.b: one verbose headline** 
Potential downside of 1a is that if we give "upcoming appearances" the same weight as "Tutorials," then "tutorials" becomes less of a page header - and since it doesn't specifically introduce new content, could make it a bit redundant. One solution to this is to break out the text into its own row above: 
![image](https://user-images.githubusercontent.com/6817579/82131138-7915e780-97a8-11ea-8ad6-befd25a14a5c.png)

**Option 1.c: one verbose headline in first row, eliminate second headline** 
We could mitigate upcoming appearances seeming redundant by taking out "online tutorials" in the row below, but it loses a bit of the distinction between the two content areas I think
![image](https://user-images.githubusercontent.com/6817579/82131144-87fc9a00-97a8-11ea-9ab6-d8d70db332c3.png): 

**Opiton 1.d.1: one simple headline in first row, one simple headline in second row** 
I went for simplicity here. I changed "tutorial" to "workshop" to try and emphasize that they're in-person events that people could join in on -- as opposed to the online tutorials available below, all while keeping it short.

![image](https://user-images.githubusercontent.com/6817579/82131193-e0cc3280-97a8-11ea-8319-1e2ae2789e86.png)

**Option 1.d.2: same as above, but with call to action** 
Same as above, but this variation with intro text that adds a call to action for the reader. (Of course we can tweak the text to make more your voice!) It's a bit messier, but a call to action/nut-graf might drive more participation. 

![image](https://user-images.githubusercontent.com/6817579/82131210-2d177280-97a9-11ea-9560-bb96fd231fdf.png)

**Comment by samanthasunne** [comment]
Let's do 1.d.1

**Comment by ludstuen90** [comment]
All done! How does this look ? 
If good, feel free to close the issue
