### ISSUE TITLE
change nav menu to white on black text

### ISSUE THREAD

**Issue by samanthasunne** [ludstuen90/samanthasunne#84]
This is just an enhancement, if it's easy enough... I'd like the nav menu, instead of black text on a transparent background, to be white text on a black background.

This will create a small black rectangle with three white words on it: About, Tutorials, Projects. The reason for this is I think it will make the menu stand out from the other content as you scroll down, like so:

![Screen Shot 2020-07-06 at 3 09 15 PM](https://user-images.githubusercontent.com/1383000/86637111-aefe6d80-bf9a-11ea-9e0b-e055e4d7f1c4.png)

**Comment by ludstuen90** [comment]
Just making the changes in the browser, here's what the end-version would look like: 
![image](https://user-images.githubusercontent.com/6817579/87205144-1ee35f80-c2dd-11ea-88ce-1cbde81be975.png)

If we keep the default behavior of a green color when selected, it would look like this: 
![image](https://user-images.githubusercontent.com/6817579/87205168-30c50280-c2dd-11ea-9156-ca63125cfb61.png)

Mobile button would look like this, not selected: 
![image](https://user-images.githubusercontent.com/6817579/87205278-74b80780-c2dd-11ea-8767-cfe9f9733c9c.png)

Selected like this. 
![image](https://user-images.githubusercontent.com/6817579/87205297-800b3300-c2dd-11ea-9b8d-f4195f597811.png)


How does this look ? If good, I can code the changes! @samanthasunne

**Comment by samanthasunne** [comment]
Can you create more space on the left and right? Right now the A in About and the s in Projects are right up against the edge of the black box

**Comment by ludstuen90** [comment]
Absolutely, here's by making the next element up with that background color: 
![image](https://user-images.githubusercontent.com/6817579/88493720-09329300-cf89-11ea-907b-ee68897c1afb.png)

Selected keeps the green branding: 
![image](https://user-images.githubusercontent.com/6817579/88493729-1780af00-cf89-11ea-81cc-e21e643ce051.png)


Mobile looks like this not selected: 
![image](https://user-images.githubusercontent.com/6817579/88493761-4bf46b00-cf89-11ea-89fd-de8bacbfd2ac.png)

And this with the menu opened up 
![image](https://user-images.githubusercontent.com/6817579/88493765-5282e280-cf89-11ea-8599-e3df72f9892a.png)


If you think it's worth it, I could look at also making the inner-menu items be a bit to the right, so as to not be right on the edge of the box

**Comment by samanthasunne** [comment]
> I could look at also making the inner-menu items be a bit to the right, so as to not be right on the edge of the box

What does this mean?

And I like the latest design, except on the mobile version the words are still flush up against the edge of the black box. Can you move the text in a bit more?

**Comment by ludstuen90** [comment]
Ah yes, we were speaking the same language! How about this? 
![image](https://user-images.githubusercontent.com/6817579/88741427-fb5e4880-d115-11ea-95f9-9976765103f2.png)

**Comment by ludstuen90** [comment]
Also, one other note -- I took as an assumption that we wanted to keep the footer nav with a white background - it looked pretty obtrusive otherwise. 

Here's how it would look (no change)
![image](https://user-images.githubusercontent.com/6817579/88744887-04074c80-d11f-11ea-9049-e01df338d5b4.png)

**Comment by samanthasunne** [comment]
Yep that looks great!

**Comment by ludstuen90** [comment]
@samanthasunne deployed to site, ready for final review

**Comment by samanthasunne** [comment]
Ok sorry to be picky, but can you make it smaller and less bold and blocky? Just significantly less intrusive if that makes sense

![Screen Shot 2020-07-31 at 2 03 23 PM](https://user-images.githubusercontent.com/1383000/89068405-c1b85800-d336-11ea-96f7-8776497d5639.png)

**Comment by samanthasunne** [comment]
Update, I still think it looks too blocky. Can we make it more smooth or streamlined looking? Sorry I don't know how to describe it

**Comment by ludstuen90** [comment]
I hear hear what you mean about it being blocky -- I had the same thought. One of the cheap and easy things we could do to make it better I think is put the background back to white, and add a small border: 
![image](https://user-images.githubusercontent.com/6817579/103143019-04673c00-46ed-11eb-84b6-00687e5b61f0.png)

This would help to visually set apart the navbar, but also make it less intrusive. 

When scrolling down, it would look like this: 
![image](https://user-images.githubusercontent.com/6817579/103143022-2c569f80-46ed-11eb-9c68-f05e5c090668.png)

Here's the same idea with a light grey border: 
![image](https://user-images.githubusercontent.com/6817579/103143053-e77f3880-46ed-11eb-94eb-cebee711fcba.png)

Black with dotted line: 
![image](https://user-images.githubusercontent.com/6817579/103143059-0da4d880-46ee-11eb-978b-d35a98864718.png)


Another way to make it look a little nicer but still go the darker route, is just change the black to a certain shade of grey:

![image](https://user-images.githubusercontent.com/6817579/103143216-6d03e800-46f0-11eb-9edf-80e2a6709715.png)

I think this makes it less intrusive, but still calls attention to itself -- the nice thing about grey instead of black is that it still manages to be separate from the darker shades of your shirt in the profile picture, the icons at the bottom of the page, and specifically the black in the NPR logo when users scroll by it: 
![image](https://user-images.githubusercontent.com/6817579/103143227-945ab500-46f0-11eb-99c4-ac86942b5c51.png)

As far as tier of options, those above would be the easiest/quickest to implement.

Then, of course, there are some higher shelf options -- add something like this creative agency's site, which has a hamburger item menu that, when clicked, makes the nav menu slide out from the side of the page: 
http://www.antro.ca/en/ 

How do these look? And of course we can keep investigating, too!

**Comment by samanthasunne** [comment]
Yes let's go with Option #1! Change the background back to white, and add a small border

**Comment by ludstuen90** [comment]
@samanthasunne  Good deal - changes deployed to site, ready for review!
